/**
 * Evidence-based therapy protocol templates for Mimio platform.
 * Extracted from MimioApp.tsx for maintainability.
 */

import type { TherapyProtocol } from "@/lib/game-types";

export const THERAPY_PROTOCOLS: TherapyProtocol[] = [
  {
    id: "adhd-basic",
    name: "DEHB Temel Dikkat Programı",
    emoji: "🎯",
    domain: "Nöroçeşitlilik",
    color: "#8b5cf6",
    duration: 6,
    description: "DEHB'li danışanlar için dikkat, çalışma belleği ve yürütücü işlev odaklı 6 haftalık kanıta dayalı müdahale protokolü.",
    targetGroup: "6-18 yaş, DEHB tanılı",
    frequency: "Haftada 3",
    weeks: [
      { week: 1, focus: "Taban ölçüm & alışma", games: ["scan", "memory"], activities: ["Dikkat egzersizleri", "Nefes tekniği"], targetScore: 5 },
      { week: 2, focus: "Sekans hafıza geliştirme", games: ["memory", "pairs"], activities: ["Sıralama aktivitesi", "İpucu stratejisi"], targetScore: 8 },
      { week: 3, focus: "Yürütücü işlev — planlama", games: ["route", "logic"], activities: ["Adım sıralama", "Görev analizi"], targetScore: 10 },
      { week: 4, focus: "Seçici dikkat güçlendirme", games: ["scan", "difference"], activities: ["Figür-zemin egzersizi", "Dikkat odaklama"], targetScore: 12 },
      { week: 5, focus: "Çift görev & entegrasyon", games: ["route", "memory"], activities: ["Çift görev kombinasyonu", "Strateji geliştirme"], targetScore: 14 },
      { week: 6, focus: "Pekiştirme & çıktı ölçümü", games: ["memory", "scan", "logic"], activities: ["Başarı portfolyosu", "Aile bilgilendirmesi"], targetScore: 16 },
    ],
    outcomes: ["Dikkat süresinde artış", "Çalışma belleği kapasitesi gelişimi", "Yürütücü işlev puanı yükselişi", "Ebeveyn/öğretmen gözlem puanları"],
  },
  {
    id: "stroke-cognitive",
    name: "İnme Sonrası Kognitif Rehabilitasyon",
    emoji: "🧠",
    domain: "Nörolojik",
    color: "#ef4444",
    duration: 8,
    description: "İnme sonrası dikkat, görsel algı ve çalışma belleği rehabilitasyonu için 8 haftalık progresif kognitif program.",
    targetGroup: "Akut sonrası inme danışanı, 18+",
    frequency: "Haftada 3-5",
    weeks: [
      { week: 1, focus: "Taban değerlendirme & yönelim", games: ["scan"], activities: ["Görsel tarama", "Çevre adaptasyonu"], targetScore: 3 },
      { week: 2, focus: "Görsel dikkat geliştirme", games: ["scan", "difference"], activities: ["Görsel arama görevi", "İhmal egzersizi"], targetScore: 5 },
      { week: 3, focus: "Hafıza stimülasyonu", games: ["pairs", "memory"], activities: ["Kart eşleme (fiziksel)", "Bellek defteri"], targetScore: 7 },
      { week: 4, focus: "Motor-kognitif koordinasyon", games: ["pulse", "difference"], activities: ["Üst ekstremite aktivitesi", "Koordinasyon egzersizi"], targetScore: 9 },
      { week: 5, focus: "Yürütücü işlev tabanı", games: ["route", "logic"], activities: ["Planlama görevi", "Problem çözme"], targetScore: 11 },
      { week: 6, focus: "Günlük yaşam aktivasyonu", games: ["memory", "route"], activities: ["GYA simülasyonu", "Ev düzenlemesi"], targetScore: 13 },
      { week: 7, focus: "İlerleme pekiştirme", games: ["scan", "pairs", "pulse"], activities: ["Karma aktivite", "Bağımsızlık hedefi"], targetScore: 15 },
      { week: 8, focus: "Çıktı değerlendirmesi & ev planı", games: ["memory", "scan"], activities: ["Ev programı eğitimi", "Bakıcı bilgilendirme"], targetScore: 16 },
    ],
    outcomes: ["Dikkat puanı artışı (LOTCA)", "Görsel ihmal azalması", "GYA bağımsızlık skoru", "FIM motor+kognitif puanları"],
  },
  {
    id: "geriatric-stimulation",
    name: "Yaşlı Kognitif Uyarım Programı",
    emoji: "🌟",
    domain: "Geriatrik",
    color: "#f59e0b",
    duration: 4,
    description: "65+ yaş grubunda kognitif rezervi destekleyen, katılımı yüksek tutmayı öncelikleyen 4 haftalık hafif-orta kognitif stimülasyon programı.",
    targetGroup: "65+ yaş, hafif kognitif şikayet",
    frequency: "Haftada 2-3",
    weeks: [
      { week: 1, focus: "Tanışma & alışma", games: ["pairs", "scan"], activities: ["Sosyal tanışma oyunu", "Anı paylaşımı"], targetScore: 4 },
      { week: 2, focus: "Bellek & dikkat kombinasyonu", games: ["memory", "difference"], activities: ["Hikaye anlatımı", "Nesne tanıma"], targetScore: 6 },
      { week: 3, focus: "Görsel algı & stratejiler", games: ["pairs", "scan", "difference"], activities: ["Strateji geliştirme", "Yardımcı ipucu eğitimi"], targetScore: 8 },
      { week: 4, focus: "Pekiştirme & ev programı", games: ["memory", "pairs"], activities: ["Topluluk aktivitesi", "Aile katılımı"], targetScore: 10 },
    ],
    outcomes: ["MoCA puanı korunumu", "Katılım & motivasyon düzeyi", "Günlük rutinlerde hafıza kullanımı", "Sosyal etkileşim kalitesi"],
  },
  {
    id: "school-readiness",
    name: "Okul Hazırlık Programı",
    emoji: "📚",
    domain: "Pediatrik",
    color: "#10b981",
    duration: 6,
    description: "Okul öncesi dönemde bilişsel, görsel ve dikkat hazırlığını destekleyen oyun odaklı 6 haftalık müdahale programı.",
    targetGroup: "4-6 yaş, okul öncesi",
    frequency: "Haftada 2",
    weeks: [
      { week: 1, focus: "Oyun kuralları & sıra bekleme", games: ["pairs"], activities: ["Yapılandırılmış oyun", "Eşleştirme aktivitesi"], targetScore: 2 },
      { week: 2, focus: "Görsel eşleştirme & sınıflandırma", games: ["difference", "pairs"], activities: ["Sınıflandırma oyunu", "Renk-şekil eşleme"], targetScore: 4 },
      { week: 3, focus: "Kısa süreli bellek", games: ["memory", "scan"], activities: ["Nesne hafıza oyunu", "Kim sakladı?"], targetScore: 5 },
      { week: 4, focus: "Dikkat yönlendirme", games: ["scan", "difference"], activities: ["Dikkat egzersizi", "Ne değişti?"], targetScore: 6 },
      { week: 5, focus: "Sıralama & plan yapma", games: ["memory", "route"], activities: ["Günlük rutin sıralaması", "Hikaye sıralama"], targetScore: 7 },
      { week: 6, focus: "Akademik hazırlık bütünleşmesi", games: ["memory", "pairs", "scan"], activities: ["Okul senaryosu oyunu", "Değerlendirme & geri bildirim"], targetScore: 8 },
    ],
    outcomes: ["Pre-akademik beceri ölçütleri", "Dikkat süresi gelişimi", "Oyun katılımı kalitesi", "Öğretmen gözlem formu puanları"],
  },
  {
    id: "executive-function",
    name: "Yürütücü İşlev Geliştirme",
    emoji: "⚙️",
    domain: "İş & Verimlilik",
    color: "#06b6d4",
    duration: 6,
    description: "Planlama, problem çözme ve inhibisyon becerilerini hedefleyen çalışan yetişkinler için 6 haftalık yürütücü işlev programı.",
    targetGroup: "18-55 yaş, iş performansı güçlükleri",
    frequency: "Haftada 2",
    weeks: [
      { week: 1, focus: "Taban değerlendirme & farkındalık", games: ["route"], activities: ["BRIEF-A farkındalık görevi", "Günlük analiz"], targetScore: 8 },
      { week: 2, focus: "Inhibisyon & dürtü kontrolü", games: ["scan", "logic"], activities: ["Dur-düşün-yap stratejisi", "Hata analizi"], targetScore: 11 },
      { week: 3, focus: "Çalışma belleği kapasitesi", games: ["memory", "route"], activities: ["N-back egzersizi (analog)", "Görev listesi yönetimi"], targetScore: 13 },
      { week: 4, focus: "Planlama & organizasyon", games: ["logic", "route"], activities: ["Proje planlama simülasyonu", "Öncelik sıralaması"], targetScore: 15 },
      { week: 5, focus: "Bilişsel esneklik", games: ["scan", "logic", "memory"], activities: ["Kural değiştirme görevi", "Perspektif alma"], targetScore: 17 },
      { week: 6, focus: "Günlük yaşama transfer", games: ["route", "logic"], activities: ["Gerçek senaryo pratiği", "Çıktı planlaması"], targetScore: 18 },
    ],
    outcomes: ["BRIEF-A yürütücü işlev puanları", "İş performansı değerlendirmesi", "Zaman yönetimi skoru", "Öz-izleme becerileri"],
  },
];

export const GOAL_PROTOCOL_MAP: Record<string, string> = {
  "dikkat": "adhd-basic",
  "odak": "adhd-basic",
  "dehb": "adhd-basic",
  "bellek": "adhd-basic",
  "hafıza": "adhd-basic",
  "inme": "stroke-cognitive",
  "felç": "stroke-cognitive",
  "nörolojik": "stroke-cognitive",
  "rehabilitasyon": "stroke-cognitive",
  "yaşlı": "geriatric-stimulation",
  "demans": "geriatric-stimulation",
  "bilişsel": "geriatric-stimulation",
  "okul": "school-readiness",
  "çocuk": "school-readiness",
  "pediatrik": "school-readiness",
  "iş": "executive-function",
  "yürütücü": "executive-function",
  "planlama": "executive-function",
};
